#!/bin/bash
# This is a simple script and will be executed on your CI system if 
# available.  Otherwise it will execute while your application is stopped
# before the build step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

echo "Installing local maven jars"

mvn install:install-file -Dfile=../../webinliner/repo/parser-1.4.jar -DgroupId=cssparser -DartifactId=parser -Dversion=1.4 -Dpackaging=jar
mvn install:install-file -Dfile=../../webinliner/repo/cssinliner-1.0.jar -DgroupId=com.leonty -DartifactId=cssinliner -Dversion=1.0 -Dpackaging=jar
